version: "3"
services:  
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    labels:
      - "traefik.enable=false"
    volumes:
      - ./mongo:/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
