version: "3"
services:
    
  postgres:
    image: fintrace/postgres-uuid
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mapviser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pdb:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
